In [1]:
import numpy as np

In [2]:
my_arr = np.arange(100000)

In [6]:
my_list = list(range(100000))

各序列乘以2进行比较测试

In [4]:
%time for _ in range(10):my_arr * 2

Wall time: 1 ms


In [7]:
%time for _ in range(10):my_list = [x * 2 for x in my_list]

Wall time: 94 ms


In [22]:
#Generate some random data
#numpy.random.rand(d0,d1,…,dn)
#rand函数根据给定维度生成[0,1)之间的数据，包含0，不包含1
#numpy.random.randn(d0,d1,…,dn)
#randn函数返回一个或一组样本，具有标准正态分布。
data = np.random.randn(2,3)
data

array([[-0.51641329,  0.10247413,  0.00883794],
       [-1.25780447,  0.51133711,  0.19929207]])

In [23]:
data * 10

array([[ -5.16413287,   1.02474132,   0.08837945],
       [-12.57804473,   5.11337111,   1.99292067]])

In [24]:
data + data

array([[-1.03282657,  0.20494826,  0.01767589],
       [-2.51560895,  1.02267422,  0.39858413]])

In [27]:
data.shape
data.dtype

dtype('float64')

4.1创建ndarray

In [28]:
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [67]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [32]:
#.ndim查看为几维数组
arr2.ndim

2

In [34]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [36]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [39]:
#???不是行列式乘法吗
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [40]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [41]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [42]:
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [44]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [46]:
#切片会自动广播，会修改源数组值
arr = np.arange(10)
arr[5]
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [48]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

布尔型索引

In [53]:
names = np.array(['Bob','Joe','Will','Bob','Will','Job','Job'])
data = np.random.randn(7,4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Job', 'Job'], dtype='<U4')

In [54]:
data

array([[ 0.50338244,  0.28085278, -0.48215954, -1.96798224],
       [ 1.21794848,  0.62670634, -0.86624034, -1.51134372],
       [-2.23437768, -0.94725622,  1.37246144, -2.12319334],
       [-0.03317182,  0.34167081, -1.48390499,  0.32654934],
       [ 0.27147158,  1.36358872, -0.10577685, -1.10229883],
       [ 1.18168603,  0.30698362, -0.74770888,  2.06836154],
       [-0.45206934,  0.77402589,  0.52006824, -1.67737393]])

In [55]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [58]:
data[names == 'Bob',3]

array([-1.96798224,  0.32654934])

花式检索

In [60]:
arr = np.zeros((8,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [64]:
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [65]:
#选行
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [68]:
#负数为倒数选行
arr[[-1,-3,-7]]

array([[7., 7., 7., 7.],
       [5., 5., 5., 5.],
       [1., 1., 1., 1.]])