元组

In [3]:
tup = (4,5,6)

In [4]:
tup

(4, 5, 6)

In [5]:
tuple([1,2,3])

(1, 2, 3)

In [6]:
a,b,c = tup
print(a)

4


In [16]:
seq = [(1,2,3),(4,5,6),(7,8,9)]
for a,b,c in seq:
    print('a={0},b={1},c={2}'.format(a,b,c))

a=1,b=2,c=3
a=4,b=5,c=6
a=7,b=8,c=9


In [19]:
a = range(10)
a = list(a)

In [25]:
a.append(10)
a.insert(2,100)
a

[0, 1, 100, 100, 100, 100, 100, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 10, 10, 10, 10]

In [27]:
a.pop(1)
a

[0, 100, 100, 100, 100, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 10, 10, 10, 10]

In [29]:
a = [1,2,5,5,8,7,6,3,1,1]
a.sort()
a

[1, 1, 1, 2, 3, 5, 5, 6, 7, 8]

In [30]:
import bisect
c = [1,2,4,8,5,1,3,4]
c.sort()
c

[1, 1, 2, 3, 4, 4, 5, 8]

In [31]:
bisect.bisect(c,5)

7

In [32]:
bisect.insort(c,7)

In [33]:
c

[1, 1, 2, 3, 4, 4, 5, 7, 8]

In [34]:
c[1:5]

[1, 2, 3, 4]

In [37]:
some_list = ['foo','bar','baz']
mapping = {}
for i,v in enumerate(some_list):
    mapping[v] = i
mapping

{'foo': 0, 'bar': 1, 'baz': 2}

In [38]:
sorted("schedule")

['c', 'd', 'e', 'e', 'h', 'l', 's', 'u']

In [39]:
seq1 = ['foo','bar','zae']
seq2 = ['one','two','three']

In [40]:
for i,(a,b) in enumerate(zip(seq1,seq2)):
    print('{0}:{1},{2}'.format(i,a,b))

0:foo,one
1:bar,two
2:zae,three


In [104]:
words = ['apple','bat','bar','atom','car']
by_letter = {}

In [105]:
for word in words:
    letter = word[0]
    by_letter.setdefault(letter,[]).append(word)
by_letter

{'a': ['apple', 'atom'], 'b': ['bat', 'bar'], 'c': ['car']}

In [10]:
strings = ['a','as','bat','car','dove']
a = [x.upper() for x in strings if len(x)>2]
a

['BAT', 'CAR', 'DOVE']

In [13]:
unique_lengths = [len(x) for x in strings]
unique_lengths

[1, 2, 3, 3, 4]

In [14]:
loc_mapping = {val : index for index, val in enumerate(strings)}
loc_mapping

{'a': 0, 'as': 1, 'bat': 2, 'car': 3, 'dove': 4}

In [15]:
all_data = [['John', 'Emily', 'Michael', 'Mary', 'Steven'],
            ['Maria', 'Juan', 'Javier', 'Natalia', 'Pilar']]

In [20]:
result = [name for names in all_data for name in names if name.count('e')>=2]
result

['Steven']

In [2]:
def f():
    a = 5
    b = 6
    c = 7
    return a,b,c
a,b,c = f()
a,b,c

(5, 6, 7)

In [6]:
states = ['Alabama','   Hen','Garmel!',' ufof hh###']

In [7]:
import re 
def clean_string(strings):
    result = []
    for value in strings:
        value = value.strip()
        value = re.sub('[!#?]','',value)
        result.append(value)
    return result

In [8]:
clean_string(states)

['Alabama', 'Hen', 'Garmel', 'ufof hh']

In [14]:
import numpy as np
data = np.random.randn(2,3)

In [15]:
data

array([[ 0.95895094,  0.01008157,  0.31172953],
       [-1.24753494,  0.239234  , -0.90060976]])

In [16]:
data*10

array([[  9.58950943,   0.10081573,   3.11729528],
       [-12.47534942,   2.39233995,  -9.0060976 ]])

In [17]:
data+data

array([[ 1.91790189,  0.02016315,  0.62345906],
       [-2.49506988,  0.47846799, -1.80121952]])

In [20]:
data = [[1,2.3,3.5,1.2,2],[1,5,4,6,5]]
arr1 = np.array(data)
arr1

array([[1. , 2.3, 3.5, 1.2, 2. ],
       [1. , 5. , 4. , 6. , 5. ]])

In [21]:
arr1.ndim

2

In [22]:
arr1.shape

(2, 5)

In [1]:
import random
position = 0
walk = [position]
steps = 1000
for i in range(steps):
    step = 1 if random.randint(0,1) else -1
    position += step
    walk.append(position)
    

In [2]:
plt.plot(walk[:100])

NameError: name 'plt' is not defined